const menuItems: {
    title: string;
    path?: string;
    icon: string;
    submenu?: { title: string; path?: string }[];
}[] = [
    {
        title: 'Салаты',
        icon: './src/assets/icons/eggplant.svg',
        submenu: [
            { title: 'Мясные салаты' },
            { title: 'Рыбные салаты' },
            { title: 'Овощные салаты' },
            { title: 'Теплые салаты' },
        ],
    },
    {
        title: 'Закуски',
        icon: 'src/assets/icons/snacks.svg',
        submenu: [
            { title: 'Мясные закуски' },
            { title: 'Рыбные закуски' },
            { title: 'Овощные закуски' },
            { title: 'Теплые закуски' },
            { title: 'Бутерброды' },
            { title: 'Фастфуд' },
        ],
    },
    {
        title: 'Первые блюда',
        icon: './src/assets/icons/pot.svg',
        submenu: [
            { title: 'Мясные супы' },
            { title: 'Овощные супы' },
            { title: 'Бульоны' },
            { title: 'Холодные супы' },
            { title: 'Диетические супы' },
        ],
    },
    {
        title: 'Вторые блюда',
        icon: './src/assets/icons/pan.svg',
        submenu: [
            { title: 'Мясные' },
            { title: 'Рыбные' },
            { title: 'Овощные' },
            { title: 'Из птицы' },
            { title: 'Из грибов' },
            { title: 'Из субпродуктов' },
            { title: 'На пару' },
            { title: 'Пельмени, вареники' },
            { title: 'Мучные гарниры' },
            { title: 'Овощные гарниры' },
            { title: 'Пицца' },
            { title: 'Суши' },
        ],
    },
    {
        title: 'Десерты, выпечка',
        icon: './src/assets/icons/хлеб-и-скалка-96 1.svg',
        submenu: [
            { title: 'Блины и оладьи' },
            { title: 'Пироги и пончики' },
            { title: 'Торты' },
            { title: 'Рулеты' },
            { title: 'Кексы и маффины' },
            { title: 'Сырники и ватрушки' },
            { title: 'Из слоеного теста' },
            { title: 'Из заварного теста' },
            { title: 'Из дрожжевого теста' },
            { title: 'Булочки и сдоба' },
            { title: 'Хлеб' },
            { title: 'Тесто на пиццу' },
            { title: 'Кремы' },
        ],
    },
    {
        title: 'Блюда на гриле',
        icon: './src/assets/icons/посудомоечная-машина-96 1.svg',
        submenu: [
            { title: 'Говядина' },
            { title: 'Свинина' },
            { title: 'Птица' },
            { title: 'Рыба' },
            { title: 'Грибы' },
            { title: 'Овощи' },
        ],
    },
    {
        title: 'Веганская кухня',
        icon: './src/assets/icons/лавровый-лист-96 1.svg',
        path: '/vegan-cuisine',
        submenu: [
            { title: 'Закуски', path: '/vegan-cuisine/Закуски' },
            { title: 'Первые блюда', path: '/vegan-cuisine/Первые блюда' },
            { title: 'Вторые блюда', path: '/vegan-cuisine/Вторые блюда' },
            { title: 'Гарниры', path: '/vegan-cuisine/Гарниры' },
            { title: 'Десерты', path: '/vegan-cuisine/Десерты' },
            { title: 'Выпечка', path: '/vegan-cuisine/Выпечка' },
            { title: 'Сыроедческие блюда', path: '/vegan-cuisine/Сыроедческие блюда' },
            { title: 'Напитки', path: '/vegan-cuisine/Напитки' },
        ],
    },
    {
        title: 'Детские блюда',
        icon: 'src/assets/icons/child-tasty-96 1.svg',
        submenu: [
            { title: 'Первые блюда' },
            { title: 'Вторые блюда' },
            { title: 'Гарниры' },
            { title: 'Выпечка' },
            { title: 'Без глютена' },
            { title: 'Без сахара' },
            { title: 'Без аллергенов' },
            { title: 'Блюда для прикорма' },
        ],
    },
    {
        title: 'Лечебное питание',
        icon: 'src/assets/icons/therapeutic_nutrition.svg',
        submenu: [
            { title: 'Детская диета' },
            { title: 'Диета №1' },
            { title: 'Диета №2' },
            { title: 'Диета №3' },
            { title: 'Диета №4' },
            { title: 'Диета №5' },
            { title: 'Диета №6' },
            { title: 'Диета №7' },
            { title: 'Диета №8' },
            { title: 'Диета №9' },
            { title: 'Диета №10' },
            { title: 'Диета №11' },
            { title: 'Диета №12' },
            { title: 'Диета №13' },
            { title: 'Диета №14' },
            { title: 'Без глютена' },
            { title: 'Без аллергенов' },
        ],
    },
    {
        title: 'Национальные',
        icon: 'src/assets/icons/international-food-96 1.svg',
        submenu: [
            { title: 'Американская кухня' },
            { title: 'Армянская кухня' },
            { title: 'Греческая кухгя' },
            { title: 'Грузинская кухня' },
            { title: 'Итальянская кухня' },
            { title: 'Испанская кухня' },
            { title: 'Китайская кухня' },
            { title: 'Мексиканская кухня' },
            { title: 'Паназиатская кухня' },
            { title: 'Русская кухня' },
            { title: 'Турецкая кухня' },
            { title: 'Французская кухня' },
            { title: 'Шведская кухня' },
            { title: 'Японская кухня' },
            { title: 'Другая кухня' },
        ],
    },
    {
        title: 'Соусы',
        icon: 'src/assets/icons/ступка-и-пестик-96 1.svg',
        submenu: [{ title: 'Соусы мясные' }, { title: 'Соусы сырные' }, { title: 'Маринады' }],
    },
    {
        title: 'Напитки',
        icon: 'src/assets/icons/drinks.svg',
        submenu: [
            { title: 'Соки и фреши' },
            { title: 'Смузи' },
            { title: 'Компоты' },
            { title: 'Кисели' },
            { title: 'Кофе' },
            { title: 'Лечебный чай' },
            { title: 'Квас' },
            { title: 'Коктейли' },
            { title: 'Алкогольные' },
        ],
    },
    {
        title: 'Заготовки',
        icon: 'src/assets/icons/паста-из-овощного-бульона.svg',
        submenu: [
            { title: 'Мясные заготовки' },
            { title: 'Рыбные заготовки' },
            { title: 'Из огурцов' },
            { title: 'Из томатов' },
            { title: 'Из грибов' },
            { title: 'Овощные заготовки' },
            { title: 'Салаты, икра' },
            { title: 'Из фруктов и ягод' },
        ],
    },
];

const logos = {
    compact: './src/assets/logo.svg',
    normal: './src/assets/logo-md.svg',
};

const person = {
    avatar: './src/assets/kate-avatar.png',
    firstName: 'Екатерина',
    lastName: 'Константинопольская',
    nickname: '@bake_and_pie',
};

export { logos, menuItems, person };
