const menuItems: {
    title: string;
    path: string;
    icon: string;
    subtitle?: string;
    subcategory?: { title: string; path?: string }[];
}[] = [
    {
        title: 'Салаты',
        icon: '/src/assets/icons/eggplant.svg',
        path: '/salads',
        subcategory: [
            { title: 'Мясные салаты', path: '/meat' },
            { title: 'Рыбные салаты', path: '#' },
            { title: 'Овощные салаты', path: '#' },
            { title: 'Теплые салаты', path: '#' },
        ],
    },
    {
        title: 'Закуски',
        icon: '/src/assets/icons/snacks.svg',
        path: '/snacks',
        subcategory: [
            { title: 'Мясные закуски', path: '/meat' },
            { title: 'Рыбные закуски' },
            { title: 'Овощные закуски' },
            { title: 'Теплые закуски' },
            { title: 'Бутерброды' },
            { title: 'Фастфуд' },
        ],
    },
    {
        title: 'Первые блюда',
        icon: '/src/assets/icons/pot.svg',
        path: '/first-dish',
        subcategory: [
            { title: 'Мясные супы' },
            { title: 'Овощные супы' },
            { title: 'Бульоны' },
            { title: 'Холодные супы' },
            { title: 'Диетические супы' },
        ],
    },
    {
        title: 'Вторые блюда',
        path: '/second-dish',
        icon: '/src/assets/icons/pan.svg',
        subcategory: [
            { title: 'Мясные' },
            { title: 'Рыбные' },
            { title: 'Овощные' },
            { title: 'Из птицы' },
            { title: 'Из грибов' },
            { title: 'Из субпродуктов' },
            { title: 'На пару' },
            { title: 'Пельмени, вареники' },
            { title: 'Мучные гарниры' },
            { title: 'Овощные гарниры' },
            { title: 'Пицца' },
            { title: 'Суши' },
        ],
    },
    {
        title: 'Десерты, выпечка',
        icon: '/src/assets/icons/хлеб-и-скалка-96 1.svg',
        path: '/desserts',
        subcategory: [
            { title: 'Блины и оладьи' },
            { title: 'Пироги и пончики' },
            { title: 'Торты' },
            { title: 'Рулеты' },
            { title: 'Кексы и маффины' },
            { title: 'Сырники и ватрушки' },
            { title: 'Из слоеного теста' },
            { title: 'Из заварного теста' },
            { title: 'Из дрожжевого теста' },
            { title: 'Булочки и сдоба' },
            { title: 'Хлеб' },
            { title: 'Тесто на пиццу' },
            { title: 'Кремы' },
        ],
    },
    {
        title: 'Блюда на гриле',
        icon: '/src/assets/icons/посудомоечная-машина-96 1.svg',
        path: '/grill',
        subcategory: [
            { title: 'Говядина' },
            { title: 'Свинина' },
            { title: 'Птица' },
            { title: 'Рыба' },
            { title: 'Грибы' },
            { title: 'Овощи' },
        ],
    },
    {
        title: 'Веганская кухня',
        subtitle:
            'Интересны не только убеждённым вегетарианцам, но и тем, кто хочет  попробовать вегетарианскую диету и готовить вкусные  вегетарианские блюда.',
        icon: '/src/assets/icons/лавровый-лист-96 1.svg',
        path: '/vegan',
        subcategory: [
            { title: 'Закуски', path: '/snacks' },
            { title: 'Первые блюда', path: '/first-dish' },
            { title: 'Вторые блюда', path: '/second-dish' },
            { title: 'Гарниры', path: '/side-dishes' },
            { title: 'Десерты', path: '/desserts' },
            { title: 'Выпечка', path: '/bakery' },
            { title: 'Сыроедческие блюда', path: '/raw-food' },
            { title: 'Напитки', path: '/drinks' },
        ],
    },
    {
        title: 'Детские блюда',
        icon: '/src/assets/icons/child-tasty-96 1.svg',
        path: '/children',
        subcategory: [
            { title: 'Первые блюда' },
            { title: 'Вторые блюда' },
            { title: 'Гарниры' },
            { title: 'Выпечка' },
            { title: 'Без глютена' },
            { title: 'Без сахара' },
            { title: 'Без аллергенов' },
            { title: 'Блюда для прикорма' },
        ],
    },
    {
        title: 'Лечебное питание',
        icon: '/src/assets/icons/therapeutic_nutrition.svg',
        path: '/medic',
        subcategory: [
            { title: 'Детская диета' },
            { title: 'Диета №1' },
            { title: 'Диета №2' },
            { title: 'Диета №3' },
            { title: 'Диета №4' },
            { title: 'Диета №5' },
            { title: 'Диета №6' },
            { title: 'Диета №7' },
            { title: 'Диета №8' },
            { title: 'Диета №9' },
            { title: 'Диета №10' },
            { title: 'Диета №11' },
            { title: 'Диета №12' },
            { title: 'Диета №13' },
            { title: 'Диета №14' },
            { title: 'Без глютена' },
            { title: 'Без аллергенов' },
        ],
    },
    {
        title: 'Национальные',
        icon: '/src/assets/icons/international-food-96 1.svg',
        path: '/nationality',
        subcategory: [
            { title: 'Американская кухня' },
            { title: 'Армянская кухня' },
            { title: 'Греческая кухгя' },
            { title: 'Грузинская кухня' },
            { title: 'Итальянская кухня' },
            { title: 'Испанская кухня' },
            { title: 'Китайская кухня' },
            { title: 'Мексиканская кухня' },
            { title: 'Паназиатская кухня' },
            { title: 'Русская кухня' },
            { title: 'Турецкая кухня' },
            { title: 'Французская кухня' },
            { title: 'Шведская кухня' },
            { title: 'Японская кухня' },
            { title: 'Другая кухня' },
        ],
    },
    {
        title: 'Соусы',
        path: '/souse',
        icon: '/src/assets/icons/ступка-и-пестик-96 1.svg',
        subcategory: [{ title: 'Соусы мясные' }, { title: 'Соусы сырные' }, { title: 'Маринады' }],
    },
    {
        title: 'Напитки',
        path: '/drinks',
        icon: '/src/assets/icons/drinks.svg',
        subcategory: [
            { title: 'Соки и фреши' },
            { title: 'Смузи' },
            { title: 'Компоты' },
            { title: 'Кисели' },
            { title: 'Кофе' },
            { title: 'Лечебный чай' },
            { title: 'Квас' },
            { title: 'Коктейли' },
            { title: 'Алкогольные' },
        ],
    },
    {
        title: 'Заготовки',
        path: '/stuff',
        icon: '/src/assets/icons/паста-из-овощного-бульона.svg',
        subcategory: [
            { title: 'Мясные заготовки' },
            { title: 'Рыбные заготовки' },
            { title: 'Из огурцов' },
            { title: 'Из томатов' },
            { title: 'Из грибов' },
            { title: 'Овощные заготовки' },
            { title: 'Салаты, икра' },
            { title: 'Из фруктов и ягод' },
        ],
    },
];

const profile = {
    avatar: '/src/assets/images/kate-avatar.png',
    firstName: 'Екатерина',
    lastName: 'Константинопольская',
    nickname: '@bake_and_pie',
    activity: {
        bookmarks: 185,
        persons: 589,
        likes: 587,
    },
};

export { menuItems, profile };
